name: Android CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'APIJSON-Android/APIJSONApp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'APIJSON-Android/APIJSONApp/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: APIJSON-Android/APIJSONApp
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: APIJSON-Android/APIJSONApp
      run: ./gradlew build
